// Code generated by go-swagger; DO NOT EDIT.

package signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHostSignersParams creates a new HostSignersParams object
// with the default values initialized.
func NewHostSignersParams() *HostSignersParams {

	return &HostSignersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHostSignersParamsWithTimeout creates a new HostSignersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHostSignersParamsWithTimeout(timeout time.Duration) *HostSignersParams {

	return &HostSignersParams{

		timeout: timeout,
	}
}

// NewHostSignersParamsWithContext creates a new HostSignersParams object
// with the default values initialized, and the ability to set a context for a request
func NewHostSignersParamsWithContext(ctx context.Context) *HostSignersParams {

	return &HostSignersParams{

		Context: ctx,
	}
}

// NewHostSignersParamsWithHTTPClient creates a new HostSignersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHostSignersParamsWithHTTPClient(client *http.Client) *HostSignersParams {

	return &HostSignersParams{
		HTTPClient: client,
	}
}

/*HostSignersParams contains all the parameters to send to the API endpoint
for the host signers operation typically these are written to a http.Request
*/
type HostSignersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the host signers params
func (o *HostSignersParams) WithTimeout(timeout time.Duration) *HostSignersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the host signers params
func (o *HostSignersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the host signers params
func (o *HostSignersParams) WithContext(ctx context.Context) *HostSignersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the host signers params
func (o *HostSignersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the host signers params
func (o *HostSignersParams) WithHTTPClient(client *http.Client) *HostSignersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the host signers params
func (o *HostSignersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HostSignersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
