// Code generated by go-swagger; DO NOT EDIT.

package signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pardot/sshsigner/proto/sshsigner/v1alpha1/httpclient/models"
)

// SignerUserSignersReader is a Reader for the SignerUserSigners structure.
type SignerUserSignersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SignerUserSignersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSignerUserSignersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSignerUserSignersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSignerUserSignersOK creates a SignerUserSignersOK with default headers values
func NewSignerUserSignersOK() *SignerUserSignersOK {
	return &SignerUserSignersOK{}
}

/*SignerUserSignersOK handles this case with default header values.

A successful response.
*/
type SignerUserSignersOK struct {
	/*Information about the cachability of the response
	 */
	CacheControl string

	Payload *models.V1alpha1UserSignersResponse
}

func (o *SignerUserSignersOK) Error() string {
	return fmt.Sprintf("[GET /sshsigner/v1alpha1/usersigners][%d] signerUserSignersOK  %+v", 200, o.Payload)
}

func (o *SignerUserSignersOK) GetPayload() *models.V1alpha1UserSignersResponse {
	return o.Payload
}

func (o *SignerUserSignersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Cache-Control
	o.CacheControl = response.GetHeader("Cache-Control")

	o.Payload = new(models.V1alpha1UserSignersResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSignerUserSignersDefault creates a SignerUserSignersDefault with default headers values
func NewSignerUserSignersDefault(code int) *SignerUserSignersDefault {
	return &SignerUserSignersDefault{
		_statusCode: code,
	}
}

/*SignerUserSignersDefault handles this case with default header values.

An unexpected error response
*/
type SignerUserSignersDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the signer user signers default response
func (o *SignerUserSignersDefault) Code() int {
	return o._statusCode
}

func (o *SignerUserSignersDefault) Error() string {
	return fmt.Sprintf("[GET /sshsigner/v1alpha1/usersigners][%d] Signer_UserSigners default  %+v", o._statusCode, o.Payload)
}

func (o *SignerUserSignersDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *SignerUserSignersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
