// Code generated by go-swagger; DO NOT EDIT.

package signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pardot/sshsigner/proto/sshsigner/v1alpha1/httpclient/models"
)

// NewSignUserKeyParams creates a new SignUserKeyParams object
// with the default values initialized.
func NewSignUserKeyParams() *SignUserKeyParams {
	var ()
	return &SignUserKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSignUserKeyParamsWithTimeout creates a new SignUserKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSignUserKeyParamsWithTimeout(timeout time.Duration) *SignUserKeyParams {
	var ()
	return &SignUserKeyParams{

		timeout: timeout,
	}
}

// NewSignUserKeyParamsWithContext creates a new SignUserKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewSignUserKeyParamsWithContext(ctx context.Context) *SignUserKeyParams {
	var ()
	return &SignUserKeyParams{

		Context: ctx,
	}
}

// NewSignUserKeyParamsWithHTTPClient creates a new SignUserKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSignUserKeyParamsWithHTTPClient(client *http.Client) *SignUserKeyParams {
	var ()
	return &SignUserKeyParams{
		HTTPClient: client,
	}
}

/*SignUserKeyParams contains all the parameters to send to the API endpoint
for the sign user key operation typically these are written to a http.Request
*/
type SignUserKeyParams struct {

	/*Body*/
	Body *models.V1alpha1SignUserKeyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the sign user key params
func (o *SignUserKeyParams) WithTimeout(timeout time.Duration) *SignUserKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sign user key params
func (o *SignUserKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sign user key params
func (o *SignUserKeyParams) WithContext(ctx context.Context) *SignUserKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sign user key params
func (o *SignUserKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sign user key params
func (o *SignUserKeyParams) WithHTTPClient(client *http.Client) *SignUserKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sign user key params
func (o *SignUserKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the sign user key params
func (o *SignUserKeyParams) WithBody(body *models.V1alpha1SignUserKeyRequest) *SignUserKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the sign user key params
func (o *SignUserKeyParams) SetBody(body *models.V1alpha1SignUserKeyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SignUserKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
