// Code generated by go-swagger; DO NOT EDIT.

package signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pardot/sshsigner/proto/sshsigner/v1alpha1/httpclient/models"
)

// NewSignerSignHostKeyParams creates a new SignerSignHostKeyParams object
// with the default values initialized.
func NewSignerSignHostKeyParams() *SignerSignHostKeyParams {
	var ()
	return &SignerSignHostKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSignerSignHostKeyParamsWithTimeout creates a new SignerSignHostKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSignerSignHostKeyParamsWithTimeout(timeout time.Duration) *SignerSignHostKeyParams {
	var ()
	return &SignerSignHostKeyParams{

		timeout: timeout,
	}
}

// NewSignerSignHostKeyParamsWithContext creates a new SignerSignHostKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewSignerSignHostKeyParamsWithContext(ctx context.Context) *SignerSignHostKeyParams {
	var ()
	return &SignerSignHostKeyParams{

		Context: ctx,
	}
}

// NewSignerSignHostKeyParamsWithHTTPClient creates a new SignerSignHostKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSignerSignHostKeyParamsWithHTTPClient(client *http.Client) *SignerSignHostKeyParams {
	var ()
	return &SignerSignHostKeyParams{
		HTTPClient: client,
	}
}

/*SignerSignHostKeyParams contains all the parameters to send to the API endpoint
for the signer sign host key operation typically these are written to a http.Request
*/
type SignerSignHostKeyParams struct {

	/*Body*/
	Body *models.V1alpha1SignHostKeyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the signer sign host key params
func (o *SignerSignHostKeyParams) WithTimeout(timeout time.Duration) *SignerSignHostKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the signer sign host key params
func (o *SignerSignHostKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the signer sign host key params
func (o *SignerSignHostKeyParams) WithContext(ctx context.Context) *SignerSignHostKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the signer sign host key params
func (o *SignerSignHostKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the signer sign host key params
func (o *SignerSignHostKeyParams) WithHTTPClient(client *http.Client) *SignerSignHostKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the signer sign host key params
func (o *SignerSignHostKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the signer sign host key params
func (o *SignerSignHostKeyParams) WithBody(body *models.V1alpha1SignHostKeyRequest) *SignerSignHostKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the signer sign host key params
func (o *SignerSignHostKeyParams) SetBody(body *models.V1alpha1SignHostKeyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SignerSignHostKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
