// Code generated by go-swagger; DO NOT EDIT.

package signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSignerUserSignersParams creates a new SignerUserSignersParams object
// with the default values initialized.
func NewSignerUserSignersParams() *SignerUserSignersParams {

	return &SignerUserSignersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSignerUserSignersParamsWithTimeout creates a new SignerUserSignersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSignerUserSignersParamsWithTimeout(timeout time.Duration) *SignerUserSignersParams {

	return &SignerUserSignersParams{

		timeout: timeout,
	}
}

// NewSignerUserSignersParamsWithContext creates a new SignerUserSignersParams object
// with the default values initialized, and the ability to set a context for a request
func NewSignerUserSignersParamsWithContext(ctx context.Context) *SignerUserSignersParams {

	return &SignerUserSignersParams{

		Context: ctx,
	}
}

// NewSignerUserSignersParamsWithHTTPClient creates a new SignerUserSignersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSignerUserSignersParamsWithHTTPClient(client *http.Client) *SignerUserSignersParams {

	return &SignerUserSignersParams{
		HTTPClient: client,
	}
}

/*SignerUserSignersParams contains all the parameters to send to the API endpoint
for the signer user signers operation typically these are written to a http.Request
*/
type SignerUserSignersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the signer user signers params
func (o *SignerUserSignersParams) WithTimeout(timeout time.Duration) *SignerUserSignersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the signer user signers params
func (o *SignerUserSignersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the signer user signers params
func (o *SignerUserSignersParams) WithContext(ctx context.Context) *SignerUserSignersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the signer user signers params
func (o *SignerUserSignersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the signer user signers params
func (o *SignerUserSignersParams) WithHTTPClient(client *http.Client) *SignerUserSignersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the signer user signers params
func (o *SignerUserSignersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *SignerUserSignersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
