// Code generated by go-swagger; DO NOT EDIT.

package signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pardot/sshsigner/proto/sshsigner/v1alpha1/httpclient/models"
)

// SignHostKeyReader is a Reader for the SignHostKey structure.
type SignHostKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SignHostKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSignHostKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSignHostKeyOK creates a SignHostKeyOK with default headers values
func NewSignHostKeyOK() *SignHostKeyOK {
	return &SignHostKeyOK{}
}

/*SignHostKeyOK handles this case with default header values.

A successful response.
*/
type SignHostKeyOK struct {
	Payload *models.V1alpha1SignHostKeyResponse
}

func (o *SignHostKeyOK) Error() string {
	return fmt.Sprintf("[POST /sshsigner/v1alpha1/hostkey][%d] signHostKeyOK  %+v", 200, o.Payload)
}

func (o *SignHostKeyOK) GetPayload() *models.V1alpha1SignHostKeyResponse {
	return o.Payload
}

func (o *SignHostKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1SignHostKeyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
