// Code generated by go-swagger; DO NOT EDIT.

package signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/pardot/sshsigner/proto/sshsigner/v1alpha1/httpclient/models"
)

// NewSignerSignUserKeyParams creates a new SignerSignUserKeyParams object
// with the default values initialized.
func NewSignerSignUserKeyParams() *SignerSignUserKeyParams {
	var ()
	return &SignerSignUserKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSignerSignUserKeyParamsWithTimeout creates a new SignerSignUserKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSignerSignUserKeyParamsWithTimeout(timeout time.Duration) *SignerSignUserKeyParams {
	var ()
	return &SignerSignUserKeyParams{

		timeout: timeout,
	}
}

// NewSignerSignUserKeyParamsWithContext creates a new SignerSignUserKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewSignerSignUserKeyParamsWithContext(ctx context.Context) *SignerSignUserKeyParams {
	var ()
	return &SignerSignUserKeyParams{

		Context: ctx,
	}
}

// NewSignerSignUserKeyParamsWithHTTPClient creates a new SignerSignUserKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSignerSignUserKeyParamsWithHTTPClient(client *http.Client) *SignerSignUserKeyParams {
	var ()
	return &SignerSignUserKeyParams{
		HTTPClient: client,
	}
}

/*SignerSignUserKeyParams contains all the parameters to send to the API endpoint
for the signer sign user key operation typically these are written to a http.Request
*/
type SignerSignUserKeyParams struct {

	/*Body*/
	Body *models.V1alpha1SignUserKeyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the signer sign user key params
func (o *SignerSignUserKeyParams) WithTimeout(timeout time.Duration) *SignerSignUserKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the signer sign user key params
func (o *SignerSignUserKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the signer sign user key params
func (o *SignerSignUserKeyParams) WithContext(ctx context.Context) *SignerSignUserKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the signer sign user key params
func (o *SignerSignUserKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the signer sign user key params
func (o *SignerSignUserKeyParams) WithHTTPClient(client *http.Client) *SignerSignUserKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the signer sign user key params
func (o *SignerSignUserKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the signer sign user key params
func (o *SignerSignUserKeyParams) WithBody(body *models.V1alpha1SignUserKeyRequest) *SignerSignUserKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the signer sign user key params
func (o *SignerSignUserKeyParams) SetBody(body *models.V1alpha1SignUserKeyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SignerSignUserKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
