// Code generated by go-swagger; DO NOT EDIT.

package signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pardot/sshsigner/proto/sshsigner/v1alpha1/httpclient/models"
)

// SignUserKeyReader is a Reader for the SignUserKey structure.
type SignUserKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SignUserKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSignUserKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSignUserKeyOK creates a SignUserKeyOK with default headers values
func NewSignUserKeyOK() *SignUserKeyOK {
	return &SignUserKeyOK{}
}

/*SignUserKeyOK handles this case with default header values.

A successful response.
*/
type SignUserKeyOK struct {
	Payload *models.V1alpha1SignUserKeyResponse
}

func (o *SignUserKeyOK) Error() string {
	return fmt.Sprintf("[POST /sshsigner/v1alpha1/userkey][%d] signUserKeyOK  %+v", 200, o.Payload)
}

func (o *SignUserKeyOK) GetPayload() *models.V1alpha1SignUserKeyResponse {
	return o.Payload
}

func (o *SignUserKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1SignUserKeyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
