// Code generated by go-swagger; DO NOT EDIT.

package signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/pardot/sshsigner/proto/sshsigner/v1alpha1/httpclient/models"
)

// SignerSignUserKeyReader is a Reader for the SignerSignUserKey structure.
type SignerSignUserKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SignerSignUserKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSignerSignUserKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSignerSignUserKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSignerSignUserKeyOK creates a SignerSignUserKeyOK with default headers values
func NewSignerSignUserKeyOK() *SignerSignUserKeyOK {
	return &SignerSignUserKeyOK{}
}

/*SignerSignUserKeyOK handles this case with default header values.

A successful response.
*/
type SignerSignUserKeyOK struct {
	Payload *models.V1alpha1SignUserKeyResponse
}

func (o *SignerSignUserKeyOK) Error() string {
	return fmt.Sprintf("[POST /sshsigner/v1alpha1/userkey][%d] signerSignUserKeyOK  %+v", 200, o.Payload)
}

func (o *SignerSignUserKeyOK) GetPayload() *models.V1alpha1SignUserKeyResponse {
	return o.Payload
}

func (o *SignerSignUserKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.V1alpha1SignUserKeyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSignerSignUserKeyDefault creates a SignerSignUserKeyDefault with default headers values
func NewSignerSignUserKeyDefault(code int) *SignerSignUserKeyDefault {
	return &SignerSignUserKeyDefault{
		_statusCode: code,
	}
}

/*SignerSignUserKeyDefault handles this case with default header values.

An unexpected error response
*/
type SignerSignUserKeyDefault struct {
	_statusCode int

	Payload *models.RuntimeError
}

// Code gets the status code for the signer sign user key default response
func (o *SignerSignUserKeyDefault) Code() int {
	return o._statusCode
}

func (o *SignerSignUserKeyDefault) Error() string {
	return fmt.Sprintf("[POST /sshsigner/v1alpha1/userkey][%d] Signer_SignUserKey default  %+v", o._statusCode, o.Payload)
}

func (o *SignerSignUserKeyDefault) GetPayload() *models.RuntimeError {
	return o.Payload
}

func (o *SignerSignUserKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RuntimeError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
