// Code generated by go-swagger; DO NOT EDIT.

package signer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUserSignersParams creates a new UserSignersParams object
// with the default values initialized.
func NewUserSignersParams() *UserSignersParams {

	return &UserSignersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserSignersParamsWithTimeout creates a new UserSignersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserSignersParamsWithTimeout(timeout time.Duration) *UserSignersParams {

	return &UserSignersParams{

		timeout: timeout,
	}
}

// NewUserSignersParamsWithContext creates a new UserSignersParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserSignersParamsWithContext(ctx context.Context) *UserSignersParams {

	return &UserSignersParams{

		Context: ctx,
	}
}

// NewUserSignersParamsWithHTTPClient creates a new UserSignersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserSignersParamsWithHTTPClient(client *http.Client) *UserSignersParams {

	return &UserSignersParams{
		HTTPClient: client,
	}
}

/*UserSignersParams contains all the parameters to send to the API endpoint
for the user signers operation typically these are written to a http.Request
*/
type UserSignersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user signers params
func (o *UserSignersParams) WithTimeout(timeout time.Duration) *UserSignersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user signers params
func (o *UserSignersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user signers params
func (o *UserSignersParams) WithContext(ctx context.Context) *UserSignersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user signers params
func (o *UserSignersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user signers params
func (o *UserSignersParams) WithHTTPClient(client *http.Client) *UserSignersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user signers params
func (o *UserSignersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *UserSignersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
