// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1SignUserKeyResponse v1alpha1 sign user key response
//
// swagger:model v1alpha1SignUserKeyResponse
type V1alpha1SignUserKeyResponse struct {

	// signed certificate to use to connect to the host, in authorized_keys format
	SignedCertificate string `json:"signed_certificate,omitempty"`
}

// Validate validates this v1alpha1 sign user key response
func (m *V1alpha1SignUserKeyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1SignUserKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1SignUserKeyResponse) UnmarshalBinary(b []byte) error {
	var res V1alpha1SignUserKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
