// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1alpha1SignUserKeyRequest v1alpha1 sign user key request
//
// swagger:model v1alpha1SignUserKeyRequest
type V1alpha1SignUserKeyRequest struct {

	// The users public key to sign, in authorized_keys format
	PublicKey string `json:"public_key,omitempty"`
}

// Validate validates this v1alpha1 sign user key request
func (m *V1alpha1SignUserKeyRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *V1alpha1SignUserKeyRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1alpha1SignUserKeyRequest) UnmarshalBinary(b []byte) error {
	var res V1alpha1SignUserKeyRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
