name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Install protoc
      run: |
        curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.12.2/protoc-3.12.2-linux-x86_64.zip
        sudo unzip protoc-3.12.2-linux-x86_64.zip -d /usr/local
        sudo chmod +x /usr/local/bin/protoc
        sudo chmod a+x /usr/local/include/google
        sudo chmod a+x /usr/local/include/google/protobuf
        sudo chmod -R a+r /usr/local/include/google

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        make build

    - name: Test
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        make test

    - name: Lint
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        make lint
